### ISSUE TITLE
Withdrawals

### ISSUE THREAD

**Issue by Quantumplation** [aiken-extra/tx_util#11]
Given the prevalence of the "withdraw 0" trick, it'd be nice to be able to tweak the withdrawals field of the script context

**Comment by ariady-putra** [comment]
Hello @Quantumplation ,

I'm interested about the "withdraw 0" trick, what is it about?

As for your suggestion, what do you think about https://github.com/ariady-putra/tx_util/commit/0402536c08f7428251f8e08fca011f11c50f2b83
?

I just exposed all ScriptContext.Transaction fields.

For `withdrawals` there are:
- `set_withdrawals` (_, withdrawals: **Dict**)
- `insert_withdrawal` (_, withdrawal_key, withdrawal_value, withdrawal_compare: **fn**)
- `insert_withdrawal_with` (_, withdrawal_key, withdrawal_value, withdrawal_compare: **fn**, withdrawal_with: **fn**)
- `union_withdrawal` (_, withdrawal_key, withdrawal_value, withdrawal_compare: **fn**)
- `union_withdrawal_with` (_, withdrawal_key, withdrawal_value, withdrawal_compare: **fn**, withdrawal_with: **fn**)
- `delete_withdrawal` (_, withdrawal_key)

The same goes for `redeemers` and `datums`, and added `set_id` and `set_fee` as well.

**Comment by Quantumplation** [comment]
If you want some logic that runs globally for the whole transaction, you can make it a staking script and then "withdraw" the staking rewards. The ledger doesn't care that there are 0 rewards to withdraw, it'll run the script regardless.

So, for example, your spending validator could just check that script X is in the list of withdrawals, and then the staking script can check that *globally* the whole transaction is valid. It saves a huge amount of execution units, makes it easier to deal with double satisfaction, etc.

And that API looks great to me!

**Comment by ariady-putra** [comment]
> If you want some logic that runs globally for the whole transaction, you can make it a staking script and then "withdraw" the staking rewards. The ledger doesn't care that there are 0 rewards to withdraw, it'll run the script regardless.
> 
> So, for example, your spending validator could just check that script X is in the list of withdrawals, and then the staking script can check that _globally_ the whole transaction is valid. It saves a huge amount of execution units, makes it easier to deal with double satisfaction, etc.

Huh, interesting on what people could come up with!
 
> And that API looks great to me!

Cool, I'll push

**Comment by ariady-putra** [comment]
https://github.com/aiken-extra/tx_util/releases/tag/1.170.202403

**Comment by Quantumplation** [comment]
@ariady-putra you might also be interested in [CIP-0112](https://github.com/cardano-foundation/CIPs/pull/749) which introduces a "proper" mechanism for this.

**Comment by ariady-putra** [comment]
Hey @Quantumplation ,
thanks for sharing! This is very valuable. There's so much for me to learn

I would also like to have a receiving validator, so that this type of contract must only contain valid UTXOs. It prevents assets being locked in a contract, and also prevent people from spamming a contract's UTXOs. I don't know about the feasibility though

**Comment by Quantumplation** [comment]
You can do a receiving validator, or close to it, by minting a token and paying it into the script

**Comment by ariady-putra** [comment]
> You can do a receiving validator, or close to it, by minting a token and paying it into the script

Hey, interesting input. It's something for me to consider
